/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker;

/**
 *
 * @author ZNK5
 */
public class Poker extends javax.swing.JFrame {

    /**
     * Creates new form Poker
     */
    public Poker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JLayeredPane();
        startLayer = new javax.swing.JLayeredPane();
        startBut = new javax.swing.JButton();
        reglasBut = new javax.swing.JButton();
        startBgLabel = new javax.swing.JLabel();
        startLogoLabel = new javax.swing.JLabel();
        gameLayer = new javax.swing.JLayeredPane();
        gameOverLayer = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1270, 700));
        getContentPane().setLayout(null);

        mainPane.setPreferredSize(new java.awt.Dimension(1270, 700));

        startLayer.setPreferredSize(new java.awt.Dimension(1270, 700));

        startBut.setText("NUEVA PARTIDA");
        startLayer.setLayer(startBut, javax.swing.JLayeredPane.MODAL_LAYER);
        startLayer.add(startBut);
        startBut.setBounds(574, 500, 122, 32);

        reglasBut.setText("REGLAS");
        startLayer.setLayer(reglasBut, javax.swing.JLayeredPane.MODAL_LAYER);
        startLayer.add(reglasBut);
        reglasBut.setBounds(597, 550, 76, 32);

        startBgLabel.setBackground(new java.awt.Color(0, 0, 0));
        startBgLabel.setOpaque(true);
        startBgLabel.setPreferredSize(new java.awt.Dimension(1270, 700));
        startLayer.add(startBgLabel);
        startBgLabel.setBounds(0, 0, 1270, 700);

        startLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        startLayer.setLayer(startLogoLabel, javax.swing.JLayeredPane.MODAL_LAYER);
        startLayer.add(startLogoLabel);
        startLogoLabel.setBounds(335, 80, 600, 333);

        mainPane.setLayer(startLayer, javax.swing.JLayeredPane.MODAL_LAYER);
        mainPane.add(startLayer);
        startLayer.setBounds(0, 0, 1270, 700);

        gameLayer.setPreferredSize(new java.awt.Dimension(1270, 700));
        mainPane.add(gameLayer);
        gameLayer.setBounds(0, 0, 1270, 700);

        gameOverLayer.setPreferredSize(new java.awt.Dimension(1270, 700));
        mainPane.setLayer(gameOverLayer, javax.swing.JLayeredPane.POPUP_LAYER);
        mainPane.add(gameOverLayer);
        gameOverLayer.setBounds(0, 0, 1270, 700);

        getContentPane().add(mainPane);
        mainPane.setBounds(0, 0, 1270, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane gameLayer;
    private javax.swing.JLayeredPane gameOverLayer;
    private javax.swing.JLayeredPane mainPane;
    private javax.swing.JButton reglasBut;
    private javax.swing.JLabel startBgLabel;
    private javax.swing.JButton startBut;
    private javax.swing.JLayeredPane startLayer;
    private javax.swing.JLabel startLogoLabel;
    // End of variables declaration//GEN-END:variables
}
